### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by lenoqt** [pdm-project/tox-pdm#17]
A bit frustrated trying to make this work, but it just doesn't, PDM works fine whenever I do ```pdm install -v``` or ```pdm sync``` 
but after I try to run tox I run into the following: 

```
See /var/folders/59/5yr8qg9n6gl1g9hqtgs127rmn4qv12/T/pdm-install-sxz9qti8.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback

============================================================================================================================================ log end ============================================================================================================================================
ERROR: could not install deps []; v = InvocationError('/usr/local/bin/pdm install -p .tox/lint --no-default --group lint --no-self', 1)
____________________________________________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________________________________________
ERROR:   lint: could not install deps []; v = InvocationError('/usr/local/bin/pdm install -p .tox/lint --no-default --group lint --no-self', 1)
```

This are my tox.ini and pyproject.toml

```
[tox]
env_list = py{310},lint,typecheck
isolated_build = true 

[testenv]
groups = test
commands =
    pytest tests/

[testenv:lint]
groups = lint
skip_install = true
commands =
    black --check bash_log2nl/
    flake9 bash_log2nl/

[testenv:typecheck]
groups = typecheck
skip_install = true
commands =
    mypy bash_log2nl/

```

```
[project]
name = "bash_log2nl"
version = "0.1.0"
description = ""
authors = [
    {name = "Gustavo Barrios", email = ""},
]
dependencies = [
    "sqlalchemy>=1.4.31",
    "pydantic[dotenv]>=1.9.0",
    "python-dotenv>=0.19.2",
    "sshtunnel>=0.4.0",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[project.urls]
homepage = ""

[project.optional-dependencies]
[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "pytest>=6.2.5",
    "pytest-cov>=3.0.0",
    "tox>=3.24.5",
    "tox-pdm>=0.3.2"]
lint = [
    "black>=22.1.0",
    "flake8>=4.0.1",
]
typecheck = [
    "mypy>=0.931",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool.pytest.ini_options]
addopts = "--cov=bash_log2nl --cov-report=term-missing"
testpaths = "tests"

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "strict"
include = ["bash_log2nl", "typings"]
exclude = ["tests"]
reportGeneralTypeIssues = false
reportConstantRedefinition = false
reportFunctionMemberAccess = false
reportImportCycles = false
reportIncompatibleMethodOverride = false
reportIncompatibleVariableOverride = false
reportMissingModuleSource = false
reportMissingParameterType = false
reportMissingTypeArgument = false
reportMissingTypeStubs = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalMemberAccess = false
reportOptionalOperand = false
reportOptionalSubscript = false
reportPrivateImportUsage = false
reportPrivateUsage = false
reportUnboundVariable = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnnecessaryComparison = false
reportUnnecessaryIsInstance = false
reportUnsupportedDunderAll = false
reportUntypedBaseClass = false
reportUnusedClass = false
reportUnusedFunction = false
reportUnusedImport = false
reportUnusedVariable = false
reportMissingImports = false

[tool.mypy]
mypy_path = "bash_log2nl"
check_untyped_defs = true
disallow_any_generics = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
no_implicit_reexport = true

[tool.black]
line-length = 88
target_version = ['py310']
```

Any help is greatly appreciated.

**Comment by frostming** [comment]
```
See /var/folders/59/5yr8qg9n6gl1g9hqtgs127rmn4qv12/T/pdm-install-sxz9qti8.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback
```

Can I have the detailed error log?

**Comment by lenoqt** [comment]
Sure. 

```
bash-log2nl on  master [!] via 🐍 v2.7.16 
❯ pdm run tox
lint create: /Users/gustavo.barrios/Documents/Projects/bash-log2nl/.tox/lint
lint pdminstall: ['lint']
ERROR: invocation failed (exit code 1), logfile: /Users/gustavo.barrios/Documents/Projects/bash-log2nl/.tox/lint/log/lint-63.log
=========================================================================================================================================== log start ===========================================================================================================================================
Synchronizing working set with lock file: 10 to add, 0 to update, 0 to remove

Install pathspec 0.9.0 failed
Install pycodestyle 2.8.0 failed
Install click 8.0.3 failed
Install platformdirs 2.4.1 failed
Install mccabe 0.6.1 failed
Install black 22.1.0 failed
Install flake8 4.0.1 failed
Install mypy-extensions 0.4.3 failed
Install tomli 2.0.0 failed
Install pyflakes 2.4.0 failed
  Retry failed jobs
Install pathspec 0.9.0 failed
Install black 22.1.0 failed
Install mypy-extensions 0.4.3 failed
Install click 8.0.3 failed
Install mccabe 0.6.1 failed
Install flake8 4.0.1 failed
Install platformdirs 2.4.1 failed
Install pycodestyle 2.8.0 failed
Install pyflakes 2.4.0 failed
Install tomli 2.0.0 failed

ERRORS:
add pathspec failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add black failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add mypy-extensions failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add mccabe failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add click failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add flake8 failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add platformdirs failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add pycodestyle failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add pyflakes failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add tomli failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'

See /var/folders/59/5yr8qg9n6gl1g9hqtgs127rmn4qv12/T/pdm-install-hdv29cnt.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback

============================================================================================================================================ log end ============================================================================================================================================
ERROR: could not install deps []; v = InvocationError('/usr/local/bin/pdm install -p .tox/lint --no-default --group lint --no-self', 1)
typecheck create: /Users/gustavo.barrios/Documents/Projects/bash-log2nl/.tox/typecheck
typecheck pdminstall: ['typecheck']
ERROR: invocation failed (exit code 1), logfile: /Users/gustavo.barrios/Documents/Projects/bash-log2nl/.tox/typecheck/log/typecheck-9.log
=========================================================================================================================================== log start ===========================================================================================================================================
Synchronizing working set with lock file: 4 to add, 0 to update, 0 to remove

Install mypy-extensions 0.4.3 failed
Install tomli 2.0.0 failed
Install typing-extensions 4.0.1 failed
Install mypy 0.931 failed
  Retry failed jobs
Install typing-extensions 4.0.1 failed
Install mypy-extensions 0.4.3 failed
Install tomli 2.0.0 failed
Install mypy 0.931 failed

ERRORS:
add typing-extensions failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add tomli failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add mypy-extensions failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'
add mypy failed:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/synchronizers.py", line 185, in install_candidate
    self.manager.install(can)
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/installers/manager.py", line 38, in install
    installer(candidate.build(), self.environment, candidate.direct_url())
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 304, in build
    self.prepare()
  File "/usr/local/Cellar/pdm/1.12.7/libexec/lib/python3.10/site-packages/pdm/models/candidates.py", line 257, in prepare
    downloaded = pip_shims.unpack_url(
TypeError: unpack_url() missing 1 required positional argument: 'verbosity'

See /var/folders/59/5yr8qg9n6gl1g9hqtgs127rmn4qv12/T/pdm-install-5tf3zdbk.log for detailed debug log.
[InstallationError]: Some package operations are not complete yet
Add '-v' to see the detailed traceback

============================================================================================================================================ log end ============================================================================================================================================
ERROR: could not install deps []; v = InvocationError('/usr/local/bin/pdm install -p .tox/typecheck --no-default --group typecheck --no-self', 1)
____________________________________________________________________________________________________________________________________________ summary ____________________________________________________________________________________________________________________________________________
ERROR:   lint: could not install deps []; v = InvocationError('/usr/local/bin/pdm install -p .tox/lint --no-default --group lint --no-self', 1)
ERROR:   typecheck: could not install deps []; v = InvocationError('/usr/local/bin/pdm install -p .tox/typecheck --no-default --group typecheck --no-self', 1)

bash-log2nl on  master [!] via 🐍 v2.7.16 took 12s 
❯ 
```

**Comment by lenoqt** [comment]
The problem is from pdm/models/candidates.py  the verbosity is not being passed and thus breaking the whole thing, I've just tested changing function call and it works fine now.

Is this intended? I also checked pip to see if they changed the function signature but I don't see any changes related to it.
```
                downloaded = pip_shims.unpack_url(
                    self.link,
                    ireq.source_dir,
                    downloader,
                    hashes=ireq.hashes(False),
```

**Comment by frostming** [comment]
what is the version of PDM and pip in the tox env?

**Comment by lenoqt** [comment]
```
❯ pdm -V && pdm run python -m pip -V 
Python Development Master (PDM), version 1.12.7
pip 22.0.2 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
```

**Comment by lenoqt** [comment]
Related to https://github.com/pdm-project/pdm/issues/874
