### ISSUE TITLE
Breaking bug in 0.7.1

### ISSUE THREAD

**Issue by kosciCZ** [pdm-project/tox-pdm#51]
Hey, 

your latest update broke our CI/CD, see attached log.

```
pip install pdm tox-pdm ansible-lint[0;m
Collecting pdm
  Downloading pdm-2.11.2-py3-none-any.whl (248 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 248.0/248.0 kB 5.5 MB/s eta 0:00:00
Collecting tox-pdm
  Downloading tox_pdm-0.7.1-py3-none-any.whl (5.3 kB)
Collecting ansible-lint
  Downloading ansible_lint-6.22.1-py3-none-any.whl (296 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.8/296.8 kB 11.3 MB/s eta 0:00:00
Collecting cachecontrol[filecache]>=0.13.0
  Downloading cachecontrol-0.13.1-py3-none-any.whl (22 kB)
Requirement already satisfied: packaging!=22.0,>=20.9 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from pdm) (23.2)
Requirement already satisfied: certifi in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from pdm) (2023.7.22)
Collecting python-dotenv>=0.15
  Downloading python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting shellingham>=1.3.2
  Downloading shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Requirement already satisfied: platformdirs in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from pdm) (3.11.0)
Collecting pyproject-hooks
  Downloading pyproject_hooks-1.0.0-py3-none-any.whl (9.3 kB)
Collecting resolvelib>=1.0.1
  Downloading resolvelib-1.0.1-py2.py3-none-any.whl (17 kB)
Collecting dep-logic<1.0,>=0.0.2
  Downloading dep_logic-0.0.4-py3-none-any.whl (26 kB)
Collecting importlib-metadata>=3.6
  Downloading importlib_metadata-7.0.1-py3-none-any.whl (23 kB)
Collecting unearth>=0.12.1
  Downloading unearth-0.12.1-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.9/42.9 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: tomli>=1.1.0 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from pdm) (2.0.1)
Requirement already satisfied: virtualenv>=20 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from pdm) (20.24.5)
Collecting installer<0.8,>=0.7
  Downloading installer-0.7.0-py3-none-any.whl (453 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 453.8/453.8 kB 26.3 MB/s eta 0:00:00
Collecting findpython<1.0.0a0,>=0.4.0
  Downloading findpython-0.4.1-py3-none-any.whl (20 kB)
Collecting requests-toolbelt
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 5.3 MB/s eta 0:00:00
Collecting blinker
  Downloading blinker-1.7.0-py3-none-any.whl (13 kB)
Collecting rich>=12.3.0
  Downloading rich-13.7.0-py3-none-any.whl (240 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.6/240.6 kB 7.1 MB/s eta 0:00:00
Collecting tomlkit<1,>=0.11.1
  Downloading tomlkit-0.12.3-py3-none-any.whl (37 kB)
Requirement already satisfied: tox>=4.0 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from tox-pdm) (4.11.3)
Collecting ansible-compat>=4.1.10
  Downloading ansible_compat-4.1.10-py3-none-any.whl (22 kB)
Collecting black>=22.8.0
  Downloading black-23.12.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 54.7 MB/s eta 0:00:00
Collecting jsonschema>=4.10.0
  Downloading jsonschema-4.20.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.7/84.7 kB 13.5 MB/s eta 0:00:00
Requirement already satisfied: requests>=2.31.0 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from ansible-lint) (2.31.0)
Collecting yamllint>=1.30.0
  Downloading yamllint-1.33.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.4/65.4 kB 8.6 MB/s eta 0:00:00
Collecting pathspec>=0.10.3
  Downloading pathspec-0.12.1-py3-none-any.whl (31 kB)
Collecting ansible-core>=2.12.0
  Downloading ansible_core-2.15.8-py3-none-any.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 58.6 MB/s eta 0:00:00
Collecting subprocess-tee>=0.4.1
  Downloading subprocess_tee-0.4.1-py3-none-any.whl (5.1 kB)
Collecting wcmatch>=8.1.2
  Downloading wcmatch-8.5-py3-none-any.whl (39 kB)
Requirement already satisfied: filelock>=3.3.0 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from ansible-lint) (3.12.4)
Requirement already satisfied: pyyaml>=5.4.1 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from ansible-lint) (6.0.1)
Collecting ruamel.yaml>=0.18.5
  Downloading ruamel.yaml-0.18.5-py3-none-any.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.4/116.4 kB 10.6 MB/s eta 0:00:00
Collecting typing-extensions>=4.5.0
  Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting cryptography
  Downloading cryptography-41.0.7-cp37-abi3-manylinux_2_28_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 64.1 MB/s eta 0:00:00
Collecting jinja2>=3.0.0
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 16.0 MB/s eta 0:00:00
Collecting importlib-resources<5.1,>=5.0
  Downloading importlib_resources-5.0.7-py3-none-any.whl (24 kB)
Collecting click>=8.0.0
  Downloading click-8.1.7-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 6.8 MB/s eta 0:00:00
Collecting mypy-extensions>=0.4.3
  Downloading mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting msgpack>=0.5.2
  Downloading msgpack-1.0.7-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (530 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 531.0/531.0 kB 21.9 MB/s eta 0:00:00
Collecting zipp>=0.5
  Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
Collecting jsonschema-specifications>=2023.03.6
  Downloading jsonschema_specifications-2023.12.1-py3-none-any.whl (18 kB)
Collecting referencing>=0.28.4
  Downloading referencing-0.32.0-py3-none-any.whl (26 kB)
Collecting attrs>=22.2.0
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 4.9 MB/s eta 0:00:00
Collecting rpds-py>=0.7.1
  Downloading rpds_py-0.16.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 46.4 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from requests>=2.31.0->ansible-lint) (3.3.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from requests>=2.31.0->ansible-lint) (2.0.6)
Requirement already satisfied: idna<4,>=2.5 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from requests>=2.31.0->ansible-lint) (3.4)
Collecting markdown-it-py>=2.2.0
  Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 kB 4.2 MB/s eta 0:00:00
Collecting pygments<3.0.0,>=2.13.0
  Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 37.2 MB/s eta 0:00:00
Collecting ruamel.yaml.clib>=0.2.7
  Downloading ruamel.yaml.clib-0.2.8-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (562 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 562.1/562.1 kB 19.6 MB/s eta 0:00:00
Requirement already satisfied: colorama>=0.4.6 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from tox>=4.0->tox-pdm) (0.4.6)
Requirement already satisfied: pyproject-api>=1.6.1 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from tox>=4.0->tox-pdm) (1.6.1)
Requirement already satisfied: pluggy>=1.3 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from tox>=4.0->tox-pdm) (1.3.0)
Requirement already satisfied: cachetools>=5.3.1 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from tox>=4.0->tox-pdm) (5.3.1)
Requirement already satisfied: chardet>=5.2 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from tox>=4.0->tox-pdm) (5.2.0)
Requirement already satisfied: distlib<1,>=0.3.7 in /pyenv/versions/3.9.18/lib/python3.9/site-packages (from virtualenv>=20->pdm) (0.3.7)
Collecting bracex>=2.1.1
  Downloading bracex-2.4-py3-none-any.whl (11 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting cffi>=1.12
  Downloading cffi-1.16.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (443 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 443.4/443.4 kB 24.7 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 9.8 MB/s eta 0:00:00
Installing collected packages: resolvelib, zipp, typing-extensions, tomlkit, subprocess-tee, shellingham, ruamel.yaml.clib, rpds-py, python-dotenv, pyproject-hooks, pygments, pycparser, pathspec, mypy-extensions, msgpack, mdurl, MarkupSafe, installer, importlib-resources, findpython, dep-logic, click, bracex, blinker, attrs, yamllint, wcmatch, unearth, ruamel.yaml, requests-toolbelt, referencing, markdown-it-py, jinja2, importlib-metadata, cffi, cachecontrol, black, tox-pdm, rich, jsonschema-specifications, cryptography, pdm, jsonschema, ansible-core, ansible-compat, ansible-lint
Successfully installed MarkupSafe-2.1.3 ansible-compat-4.1.10 ansible-core-2.15.8 ansible-lint-6.22.1 attrs-23.2.0 black-23.12.1 blinker-1.7.0 bracex-2.4 cachecontrol-0.13.1 cffi-1.16.0 click-8.1.7 cryptography-41.0.7 dep-logic-0.0.4 findpython-0.4.1 importlib-metadata-7.0.1 importlib-resources-5.0.7 installer-0.7.0 jinja2-3.1.2 jsonschema-4.20.0 jsonschema-specifications-2023.12.1 markdown-it-py-3.0.0 mdurl-0.1.2 msgpack-1.0.7 mypy-extensions-1.0.0 pathspec-0.12.1 pdm-2.11.2 pycparser-2.21 pygments-2.17.2 pyproject-hooks-1.0.0 python-dotenv-1.0.0 referencing-0.32.0 requests-toolbelt-1.0.0 resolvelib-1.0.1 rich-13.7.0 rpds-py-0.16.2 ruamel.yaml-0.18.5 ruamel.yaml.clib-0.2.8 shellingham-1.5.4 subprocess-tee-0.4.1 tomlkit-0.12.3 tox-pdm-0.7.1 typing-extensions-4.9.0 unearth-0.12.1 wcmatch-8.5 yamllint-1.33.0 zipp-3.17.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
[32;1m$ tox -e pylint[0;m
pylint: internal error
Traceback (most recent call last):
  File "/pyenv/versions/3.9.18/lib/python3.9/site-packages/tox/session/cmd/run/single.py", line 46, in _evaluate
    tox_env.setup()
  File "/pyenv/versions/3.9.18/lib/python3.9/site-packages/tox/tox_env/api.py", line 247, in setup
    self._setup_env()
  File "/pyenv/versions/3.9.18/lib/python3.9/site-packages/tox_pdm/plugin.py", line 45, in _setup_env
    if self.conf["skip_install"]:
  File "/pyenv/versions/3.9.18/lib/python3.9/site-packages/tox/config/sets.py", line 118, in __getitem__
    return self.load(item)
  File "/pyenv/versions/3.9.18/lib/python3.9/site-packages/tox/config/sets.py", line 128, in load
    config_definition = self._defined[item]
KeyError: 'skip_install'
  pylint: FAIL code 2 (0.63 seconds)
  evaluation failed :( (0.88 seconds)
```

Looking at the changelog, I'd guess it's because skip_install is somehow assumed to be present, although according to [tox docs](https://tox.wiki/en/4.11.4/config.html#skip_install) it is optional and has a default value of `False`. Could you please revert/fix this change?

**Comment by kosciCZ** [comment]
Thanks for the quick fix!
